### ISSUE TITLE
Running 'make install' results in error.

### ISSUE THREAD

**Issue by coquizen** [samdoshi/.xmonad#1]
'stack build
Stack looks for packages in the directories configured in the 'packages' variable defined in your stack.yaml
The current entry points to /home/caninodev/.xmonad/vendor/xmonad-contrib/ but no .cabal file could be found there.
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1'

As this appears to be a custom install of xmonad-contrib, you may want to consider using your xmonad-contrib as a git submodule of this git.'

**Comment by samdoshi** [comment]
This is just my personal config of XMonad. If you're looking to try it out anyway, then it looks the the readme missed out the step to checkout the submodules.

So either...

```
cd ~/.xmonad
git submodule init
git submodule update
```

or clone the repo again, but with:

```
git clone --recursive git@github.com:samdoshi/.xmonad.git ~/.xmonad
```

Does that sort you out?

---

edit: nevermind, I haven't pushed my commits to samdoshi/xmonad and samdoshi/xmonad-contrib yet. Give me 5 mins.

---

edit 2: changes pushed
